Algoritmo "crescente"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 


Var

   x, y : inteiro

Inicio

  escreval("Digite dois numeros: ")
  leia(x)
  leia(y)

  enquanto x <> y faca
    se x > y entao
     escreval("DECRESCENTE! ")
    senao
     escreval("CRESCENTE!")
    fimse
  escreval("Digite outros dois numeros:")
  leia(x)
  leia(y)
  fimenquanto


Fimalgoritmo